
//! Autogenerated weights for `pallet_currency`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-03-07, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/phuquocdog-node
// benchmark
// --chain
// dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_currency
// --extrinsic=*
// --steps
// 50
// --repeat
// 20
// --output
// pallets/currency/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_currency`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_currency::WeightInfo for WeightInfo<T> {
	// Storage: Currency Currency (r:1 w:1)
	// Storage: Currency Currencies (r:1 w:1)
	fn add_currency() -> Weight {
		(41_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Currency Currency (r:1 w:0)
	// Storage: Currency Accounts (r:1 w:1)
	fn update_balance(s: u32, ) -> Weight {
		(46_910_000 as Weight)
			// Standard Error: 6_000
			.saturating_add((6_000 as Weight).saturating_mul(s as Weight))
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
